Added 0.28.2 locales for bosnian, made from serbian
Platoniq/decidim-b4m pull request #8
Opened 2024-12-19 15:22 UTC by HHassig

Steps taken:

1. Download [Serbian pack](https://crowdin.com/project/decidim/sr-CS)
2. Find all translated instances in Serbian, translate to Bosnian
3. Upload new [Bosnian file](https://crowdin.com/project/decidim/bs)
4. Download all 0.28.2 bosnian .yml files
5. Add them to config/locales/*.bs.yml

No overrides specs have been done

2025-01-30 16:21 UTC, HHassig commented
In the end, the source used was all of the `sr-CS.yml` files from [here](https://github.com/decidim/decidim/tree/d89bccc5962740075ee47661125521c22e30c8ba)

2025-01-30 16:24 UTC, fblupi requested changes

2025-01-30 16:24 UTC, fblupi commented on Gemfile.lock
> +  decidim-decidim_awesome
Why this change? Undo it, please

2025-01-31 08:46 UTC, fblupi requested changes

2025-01-31 08:46 UTC, fblupi commented on config/locales/pages.bs.yml
> +sr:
```suggestion
bs:
```

2025-01-31 08:46 UTC, fblupi commented on config/locales/sortitions.bs.yml
> +sr:
```suggestion
bs:
```

2025-01-31 08:46 UTC, fblupi commented on config/locales/surveys.bs.yml
> +sr:
```suggestion
bs:
```

2025-01-31 08:46 UTC, fblupi approved these changes

2025-01-31 08:59 UTC, merged